### ISSUE TITLE
After user submit ATI for review

### ISSUE THREAD

**Issue by tohuynh** [QualitativeDataRepository/AnnoREP-Frontend#24]
As I understand it, after the user submits an ATI project for review, the end goal is to eventually copy their private annotations to the ATI group with QDR as the author. This currently can't be done because users won't and shouldn't have access to QDR's API token or the admins won't have access to the users' private annotations in order to export them to the ATI group.

### Possible solution
When users request for review, AnnoRep will copy their annotations to the ATI Staging group with QDR as the author (it can public or private, it doesn't matter). After reviewing the ATI project, an admin (assuming the admin has access to annotations on ATI staging) can export them to the ATI group.

How should the annotations on ATI staging stay in sync with the user's private annotations? That is, during the review process, an admin may ask the user to update an annotation. How should AnnoRep update the annotations on ATI staging to stay in sync with the user's annotations? We just need to make sure that when an admin finally exports annotations to the ATI group, they need to be exactly what the users want to be exported.

cc @adam3smith @nniiicc for feedback or thoughts on other solutions.

**Comment by nniiicc** [comment]
@tohuynh - thanks for keeping this moving. 

I think we should break the review into two stages 
1. Request review: The user requests an admin review  - the admin pulls into the ATI staging and gives feedback and the user makes any necessary changes. The admin then erases them from staging.  
2. Request publication: The user requests admin to publish the updated (and final) annotations. The admin again pulls the  annotations into the ATI staging, double checks them, and then publishes the annotation to the QDR ATI group 

Does that make sense?

**Comment by tohuynh** [comment]
@nniiicc  "the admin pulls annotations into the ATI staging ". To clarify, this step can't be done manually by an admin, since the admin doesn't have access to the user's private annotations. It could be done by AnnoRep after the user clicks "submit for review". We would have to provide AnnoRep with an admin API token to write annotations to ATI Staging. Another option is to have users initially post annotations to ATI Dev group (with the author being the user and the annotations are public to the group). All members of ATI Dev would be able to see annotations though. Note: I asked a question on Hypothesis slack, if it is possible to allow the owner/admin of a group to see all annotations posted to the group including private ones? If the answer is yes, we could make the annotations private in the ATI Dev group.

How would the admin provide feedback to the user in step 1?

How would the admin erase annotations from staging? By manually erasing them using the Hypothesis annotation sidebar?

**Comment by adam3smith** [comment]
> It could be done by AnnoRep after the user clicks "submit for review". We would have to provide AnnoRep with an admin API token to write annotations to ATI Staging

I think this is the way to go. If we're worried about security, this could be a different account than the qdr account that handles live ATI annotations

> How would the admin provide feedback to the user in step 1?

With the option above, the admin could both modify annotations and add replies to them, right? The question is then how would the user see those? I imagine they need to join the staging group? One issue with that is that I don't know if it's possible to _remove_ a user from a group

> How would the admin erase annotations from staging? By manually erasing them using the Hypothesis annotation sidebar?

Could we automate this? Clicking on the trash & confirm 40 times isn't exactly my vision of scalable ;)

**Comment by tohuynh** [comment]
> With the option above, the admin could both modify annotations and add replies to them, right?

Yes, I think so. When the user submits for review their annotations are copied to ATI staging using the admin API token. The admin logins into AnnoRep using the same API token, thus allowing them to modify annotations or reply to them.

 > I imagine they need to join the staging group?

Yes, I think so.

> One issue with that is that I don't know if it's possible to remove a user from a group

I don't see the option to remove a member in the web UI, but there is an API endpoint to remove a member from a group. So, I think it's possible.

> Could we automate this? Clicking on the trash & confirm 40 times isn't exactly my vision of scalable ;)

Yes for sure.

Another solution to explore is to create a new group for each ATI project (using the admin API token) and have the user joins the group. There are hypothesis API endpoints to create a new group and add members to the group. This way the copied annotations are visible only to the user and admin. The admin can provide feedback that users would be able to see. The way this would work is: 1)user submits for review 2) annotations are copied to the new group using admin API token 3)user is added the new group 4)admin modify copied annotations or add replies to them 5)admin can delete annotations and group

Issue about this approach: is there a limit on the number of groups a user can create?

**Comment by adam3smith** [comment]
OK, we're now using staging & it's working nicely
