### ISSUE TITLE
Annotations are sometimes orphaned although they're in the paper

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#45]
This seems to happen when the client loads before the iframe with the hypothesis client. 
This isn't a problem with the annotations: switching to a different group and back fixes this, so the solution would likely be to load the hypothesis client later or force refresh it (if possible)

**Comment by tohuynh** [comment]
This issue seems to still exist in local development. It doesn't seem to exist on stage or production. Regardless I'll reopen it.

**Comment by adam3smith** [comment]
We're still seeing this occasionally, yes

**Comment by tohuynh** [comment]
@adam3smith I think the recent PR #93 fixed the issue.

**Comment by adam3smith** [comment]
Indeed no longer seeing this, so closing the issue
