### ISSUE TITLE
Improve add datasource dialog

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#46]
Exact details of this depend on how https://github.com/QualitativeDataRepository/AnnoREP-Frontend/issues/41 is implemented

Several things came up in testing:

1. The icon is too hard to find. Let's try to just add "Add data sources" text next to the icon that opens the dialog: 
![image](https://user-images.githubusercontent.com/128986/156246628-03b3320a-8e6b-46e9-a73d-8ae3062a5a57.png)
The hover-text is too hard to find.

2. Once opened, it's not clear how people use these sources. Let's change the text at the top to: "Copy the data source URL and paste it into an annotation on the right"

3. If possible, allow to add files here as per #41 ). If that's not reasonably feasible, let's be clearer about this. "Add/remove associated data sources" is clearer than "modify" I think

**Comment by tohuynh** [comment]
4. If the ATI project has no data sources, instead just display that there are no data sources, also provide a link for them to create data sources.
