### ISSUE TITLE
Add Refresh button in add datasource dialog

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#66]
## Use Case

A use opens the sidebar, clicks add/remove data source, adds one or more files in QDR. Those files then don't show up

## Solution

Can we add a reload button that just reloads the page on the right?

## Alternatives

If not, adding a "[refresh page]() to show newly added files" message might work, but it less elegant.

**Comment by tohuynh** [comment]
The request is to add a button that refreshes the list of available data sources?

> Can we add a reload button that just reloads the page on the right?

Do you mean on the right of "Add/remove associated data sources"?

Text of button should be "Refresh" or just refresh icon 
![image](https://user-images.githubusercontent.com/37560480/158265924-81c4bf08-03c4-47b6-ba19-4ecdacd9fabd.png)
?

**Comment by adam3smith** [comment]
Yes, that's exactly where. Let's try the icon. I think that's pretty recognizable

**Comment by adam3smith** [comment]
Beautiful!
