### ISSUE TITLE
For discussion: Further Tweaks on New ATI Project Page

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#67]
Follows #54 
The page is already much improved, but I'd like to discuss some additional changes. I'd like to hear from both @nniiicc and @tohuynh before we decide on these, but here's my current thinking based on testing.

We observed the following issues:
1. Users are confused why there are two projects
2. Users try to type into the Create new QDR Project bar, often thinking they're adding a project title here
3. We haven't tested with the more visible button, but I suspect this is still not clear to users
4. People are unclear about the relationship between the QDR Data Project and the Manuscript.

Here's a mock-up for an updated page (don't mind design details; hacked together in HTML):
![image](https://user-images.githubusercontent.com/128986/158001122-3171e0fc-afd3-41f7-93db-5f1a596d413a.png)

**Comment by adam3smith** [comment]
It would also be great if we could refresh just the list of data projects rather than the whole page (which removes added manuscript files, e.g.)

**Comment by tohuynh** [comment]
The text below "New ATI Project" sounds a like a good idea. It gets across the point that to create an ATI project, users need to select a QDR data project and a manuscript.

> Users are confused why there are two projects

Would consistently using "QDR data project" throughout this page help make it less confusing? I shortened "QDR data project" to "data project" due its proximity to the label "Link to QDR data project" of the combo box. I think "Link to QDR data project" text could be confusing. Change the label to "QDR data project"? The placeholder "Please choose a QDR data project" provides a hint as to what they are supposed to do.

>It would also be great if we could refresh just the list of data projects rather than the whole page (which removes added manuscript files, e.g.)

Users could find the newly created data project by searching for it -- typing some text and press "Enter". I don't think there's any hint that they could do this (except the blinking cursor when the open the combo box). Yes, I can modify "Refresh page" to refresh just the list of QDR data projects. Any recommendations for the what the text should be -- "Refresh ____"?

---
Could you clarify the intent of "Create New Data Droject", and the double edged arrows in the above image?

**Comment by adam3smith** [comment]
> Would consistently using "QDR data project" throughout this page help make it less confusing? I shortened "QDR data project" to "data project" due to its proximity to the label "Link to QDR data project" of the combo box. 

I actually think the shortening makes sense and would leave it. If it's under a sort of "heading" as I have it now, I think that's clearer. Also note that I've changed the "Create" button at the bottom to Create **ATI** Project, which I think should help.

> I think the "Link to QDR data project" text could be confusing. Change the label to "QDR data project"? The placeholder "Please choose a QDR data project" provides a hint as to what they are supposed to do.

If you add the bold bit above as I have it, could you just leave "Link to QDR data project" out entirely? It should hopefully be pretty clear between the header, the button on the right, and the text in the box?

> Yes, I can modify the "Refresh page" to refresh just the list of QDR data projects. Any recommendations for what the text should be -- "Refresh ____"?

Cool. "Refresh data projects" I think?

> Could you clarify the intent of "Create New Data Project", 
That's currently just represented by the three dot menu. I don't think users recognize that. I'd like "Create New Data Project" written out on the button.

> and the double-edged arrows in the above image?

That shouldn't actually appear, I just mean that to show that I've switched those two elements' order from the current page

**Comment by tohuynh** [comment]
> If you add the bold bit above as I have it, could you just leave "Link to QDR data project" out entirely? It should hopefully be pretty clear between the header, the button on the right, and the text in the box?

I can't remove "Link to QDR data project", for accessibility reasons -- every input field requires a label. But if I make "1. QDR data project" the label of the combo box and bold it, I'm going against the design recommendations of the design system I'm using (which make it inconsistent with the other forms input label of the app). So let's leave the label "Link to QDR data project" and let "1. QDR data project" be the section header of the combo box and "Don't have a QDR data project?"

> That's currently just represented by the three dot menu. I don't think users recognize that. I'd like "Create New Data Project" written out on the button.

The current 3 dots button doesn't create a new data project, but it adds more data projects to the combo box (sort of a pagination feature to make page initially load faster). 3 dots is often used to signal "More options"? I could just write out "More data projects" if you prefer.

**Comment by adam3smith** [comment]
I don't have the app open, but what I remember is that clicking on the dots opens a "create new" button. Are you sure that's not the case?

**Comment by tohuynh** [comment]
Yes I moved "create new" so that it's underneath "Don't have a QDR data project?"
https://qualitativedatarepository.github.io/AnnoREP-Frontend/?path=/story/ati-new-ati-project-form--with-show-more-datasets

With only one option left (previously, it was "create new" and "show more data projects") I decided to just turn 3 dots into a simple button.

**Comment by tohuynh** [comment]
Are we good for me to implement the changes requested here?

- Add text "An ATI project has two components..."
- Add section header "1. QDR data project"
- "Manuscript" -> "2. Manuscript"
- Reorder combo box and "Don't have a QDR data project?"
- "Refresh" -> "Refresh data projects", and refresh just the list of data projects, not the entire page
- Add "ATI" to submit button

**Comment by adam3smith** [comment]
Yes, thanks for checking. Let's go with that

**Comment by adam3smith** [comment]
This looks great! We'll have to see if the text at the top works (Diana has some doubts), but for now this is done
