### ISSUE TITLE
Copy Data Source icon disappears

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#72]
Even on a fairly big screen, the "Copy data source" icon disappears and the horizontal scrollbar is hard to see:
![image](https://user-images.githubusercontent.com/128986/158659147-1718babe-8b31-450a-86f4-7f303f85723f.png)

Some ideas:
- Turn the whole title into a copy data source link (though might be confusing)
- Auto-resize the data source bar (though might get too big?)
- More aggressively wrap the title strings (might look weird if we wrap in the middle of a word; but at a minimum we could wrap on underscores, too)

Thoughts?

**Comment by tohuynh** [comment]
How common are ellipses in file names? What about clipping the title, but showing the full title on hover?

> More aggressively wrap the title strings (might look weird if we wrap in the middle of a word; but at a minimum we could wrap on underscores, too)

Looks like it's currently wrapping on "-". But wrapping on "_"  won't have 100% coverage. There could still be a series of characters that don't wrap and causes the copy button to be initially out of sight.

I think the ellipsis is the best option so far.

**Comment by adam3smith** [comment]
> What about clipping the title, but showing the full title on hover?

Ah yes, I think that's work nicely, good idea.

**Comment by adam3smith** [comment]
This works great, thanks!
