### ISSUE TITLE
After Export to Different URL, provider hyp.is/go link

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#73]
In the success message after copying/exporting the annotations to a destination URL, could we provide the Hypothesis-enabled URL, i.e. 
`https://hyp.is/go?url=<destinationURL&group=<groupID>` , where `__world__` is the group ID for public. That way users know how to link to this directly. 

So add something like "Your manuscript with ATI annotations can be accessed at..." (or similar language)

**Comment by tohuynh** [comment]
Is there documentation for creating a hyp.is/go URL? I can't seem to find it.

**Comment by adam3smith** [comment]
https://github.com/hypothesis/bouncer#route-syntaxapi

**Comment by tohuynh** [comment]
The main intent is to allow users to copy the link? or visit the link?

I was thinking of displaying an `a` element instead of displaying the long URL (if users just want to visit the URL).

**Comment by adam3smith** [comment]
copying is definitely a major use case -- the idea would be that you upload a paper to (e.g.) your homepage and then share the annotated version with others -- so you'd be sharing the `hyp.is` link

**Comment by tohuynh** [comment]
@adam3smith Any feedback on this success message?

![image](https://user-images.githubusercontent.com/37560480/158896546-af40a1c1-6c1c-48a2-84a6-de6436c0ef6f.png)

With this users can visit the destination URL or copy it to the clipboard.

I wanted to avoid displaying possibly long URL.

**Comment by adam3smith** [comment]
I like the message. The copy icon has a hover-over text, I assume? 
The only thing I wonder is if it's possible to have it be a bit closer to the URL rather than right-aligned? I realize that might be tricky while scaling, but it took quite some time until I spotted it, and I was looking...

**Comment by tohuynh** [comment]
It has a "Copy URL to clipboard" on hover. The placement of the button (an action regarding the message) is in the best position and it should have a consistent placement across all notification messages. I think changing the copy icon to "Copy URL" will make it more visible?

**Comment by adam3smith** [comment]
>  I think changing the copy icon to "Copy URL" will make it more visible?

Could I see them side-by-side? I like the consistency of the copy icon, which we use elsewhere, too.

Also curious if @nniiicc has any thoughts on language. The one thing I wish could be clearer is that this is a special URL that calls up the annotations, but I am not sure that's possible without some lengthy text (that I definitely don't want)

**Comment by tohuynh** [comment]
![image](https://user-images.githubusercontent.com/37560480/158918242-d9fdb050-8e34-42c9-89d6-e7c15e9b25e4.png)

Is this a little better?

Previously, I made all notification messages have 100% width.

**Comment by tohuynh** [comment]
![image](https://user-images.githubusercontent.com/37560480/158920084-de22d2c5-a899-44ef-a029-e3066084f953.png)

(Another attempt to make the copy button more visible by adding a border)

**Comment by adam3smith** [comment]
Thanks for these options! Let's try with the shortened banner with the unframed copy icon. The frame does highlight it, but to me it looks... off. We can always add back if we find that users aren't spotting/recognizing the icon.

**Comment by adam3smith** [comment]
Tested on Stage --- looks great
