### ISSUE TITLE
Can we add a FavIcon?

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#74]
Doesn't have to be fancy, maybe just AnnoREP in white in in a square (so 
![image](https://user-images.githubusercontent.com/128986/158686061-5d1382cb-a6dd-410f-b414-846f21035567.png)
) with blue background

**Comment by tohuynh** [comment]
Sure, could favicon be created for me? I have no design experience

**Comment by adam3smith** [comment]
[Anno-REP_favicon_package_v0.16.zip](https://github.com/QualitativeDataRepository/AnnoREP-Frontend/files/8279022/Anno-REP_favicon_package_v0.16.zip)

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

**Comment by tohuynh** [comment]
Thanks for creating these files.

![image](https://user-images.githubusercontent.com/37560480/158722793-1719324a-1a0e-4d77-8425-5f5ea0c4880e.png)

"AnnoREP" doesn't look legible in some of the smaller sizes?

**Comment by adam3smith** [comment]
Yeah, I considered that. We don't have a logo, though, so this just seems like the most pragmatic solution and w the color it's recognizable, I think.
