### ISSUE TITLE
Building Summary pages with many items is slow & resource intensive

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#87]
We haven't narrowed this down very precisely, but can consistently replicate a project with ~50 data files causing a 504 on production . Other projects with many data files are also quite slow to build the summary page.

**Comment by tohuynh** [comment]
Probably something to do with the data project zip file. For this page, the server will try to assemble a zip file for users to download, which can be resource intensive if there are 50 files.

**Comment by tohuynh** [comment]
What happens if you try to "download data project" on QDR?

**Comment by adam3smith** [comment]
It's giant -- 1.7BG -- but downloads without any noticeable impact on the site (which has a very robust machine on the server, of course, though)

**Comment by tohuynh** [comment]
Some options we can explore:

- scale AnnoRep vertically (increase the memory capacity of AnnoRep server)
- Allow users to download the data project zip on the client-side, but I need to break my rule of never using the user's API token on the client side. AnnoRep server does all API calls and never exposes the API token in client-side code.
- Remove download data project button

**Comment by adam3smith** [comment]
I think we can remove the download data project button. No one asked about this and the people who did were confused by what they got (expecting an annotated manuscript).
For this functionality
- we offer the annotation download
- people can download the files from DV

so this really just turns 1 step into 2.

**Comment by adam3smith** [comment]
@nniiicc would you chime in on this -- I think you already liked the idea of a download, so maybe I'm not thinking of usecases

**Comment by nniiicc** [comment]
I am in favor of removing the download data project button - I agree with your reasoning above

**Comment by tohuynh** [comment]
Sounds good, I will remove the button
