### ISSUE TITLE
Number annotations

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#92]
Users frequently request numbering annotations for easier conversation/citation. 

Open questions:
- Layout/position for the number
- At what point are the number getting added -- we can't constantly renumber, so maybe when submitting for review (or exporting)?

**Comment by tohuynh** [comment]
Hmm, not entirely sure about the details of this question.

Do you mean to automatically add a number to the beginning of the text of an annotation?

**Comment by adam3smith** [comment]
Yes, exactly. We've agreed on a layout, so we'd want the header to be 

```
<a href="https://qdr.syr.edu/ati"><img src="https://qdr.syr.edu/drupal_data/public/ati_banner_long.png"/></a>
<br><b>AN$n</b></br>
```

where `$n` is the annotation number. I think the logical step would be to do this as part of the export step, and I'd be inclined to add another toggle for this 
![image](https://user-images.githubusercontent.com/128986/198341602-b2d93b35-0179-44d1-82fb-0d9bb7bab744.png)

What do you think? Is that reasonably doable?

**Comment by tohuynh** [comment]
Adding a number to annotation's text isn't an issue -- it's easy to add. And adding another toggle UI to export annotations form is doable.

But how will the order of the annotations be determined -- which annotation gets the number 1?

#### Potential orders
1. Order by `updated` datetime of the annotation. I'm OK with either ascending or descending order.
2. Order by `created` datetime of the annotation.
3. Order by how they appear in the Hypothesis client. Meaning the visibly top annotation in the Hypothesis client gets the number 1.

Options 1 and 2 are the easiest to implement and require minor code changes.

Option 3 would require fetching all the annotations for a URI and possibly looking into each annotation's details to determine their correct order. There's also the issue of papers having two or more columns of text -- how will the order be determined then?

(Just a note: currently when exporting annotations, AnnoRep will fetch a batch of annotations that are ordered by `updated` datetime and then export the batch. The process is repeated for the next batch, and so on. Option 3 would require this batching process to change because it would require all annotations fetched to determine the correct order.)

**Comment by adam3smith** [comment]
Unforutnately, this really only makes sense as 3)  , i.e. by `Location` in Hypothesis terms (the AnnoREP client also allows soring by newest/oldest, but we don't care about that). So I'm guessing you'd have to retrieve all annotations, sort, then export them in batch -- sorry for the hassle, but people _really_ want this...

**Comment by tohuynh** [comment]
For 3, if AnnoREP has to fetch all annotations to sort them, there's also the issue of having a large number of annotations in memory. It might not be an issue for regular users, but I'm not particularly eager to leave it up to users to error the app by exporting many annotations that exceed the app's memory limit.

Since the goal of this feature is to allow easier communication, have you already exhausted other alternatives to label the annotations (without having to sort annotations)?

For 3, it doesn't look like it's possible to sort by `Location` when using their [`/search`](https://h.readthedocs.io/en/latest/api-reference/v1/#tag/annotations/paths/~1search/get) endpoint. Do you think we could ask for this feature? It would be a much cleaner solution than AnnoREP sorting them.

**Comment by adam3smith** [comment]
> For 3, it doesn't look like it's possible to sort by Location when using Hypthesis [/search](https://h.readthedocs.io/en/latest/api-reference/v1/#tag/annotations/paths/~1search/get) endpoint. Do you think we could ask for this feature? It would be a much cleaner solution than AnnoREP sorting them.

yeah, I looked at that, too -- I agree that'd be the most elegant solution, but I'm not sure we can rely on them implementing this in any given time.

>  It might not be an issue for regular users, but I'm not particularly eager to leave it up to users to error the app by exporting many annotations that exceed the app's memory limit.

Can you estimate the rough order of magnitude at which we'd run into this issue? Could we built a failsafe into the app, along the lines of:

> Retrieve total number of observations

If > 200 (as an example large number)

> I'm sorry, AnnoREP can't number annotations for projects with more than 200 annotations

**Comment by tohuynh** [comment]
> Can you estimate the rough order of magnitude at which we'd run into this issue?

It depends on the memory of the machine the app is running on and the average annotation size.

We had a similar [issue](https://github.com/QualitativeDataRepository/AnnoREP-Frontend/issues/87), where the task's required memory exceeded the machine's memory capacity. So around 2GB of total annotations?

**Comment by tohuynh** [comment]
> yeah, I looked at that, too -- I agree that'd be the most elegant solution, but I'm not sure we can rely on them implementing this in any given time.

Just FYI, I asked their slack channel how easy it would be for them to add the feature.

**Comment by adam3smith** [comment]
> So around 2GB of total annotations?

We can still put a failsafe in there, but since the annotations are plaintext, 2GB of annotations are ~160 million words -- that seems fantastically unlikely (as opposed to attachments, which can be quite big)

**Comment by tohuynh** [comment]
> Since the goal of this feature is to allow easier communication, have you already exhausted other alternatives to label the annotations (without having to sort annotations)?

I'll proceed with option 3 if there aren't further thoughts on this.

> 2GB of annotations are ~160 million words

Is 800,000 (80 million / 100 avg words per annotation) as a max number of annotations allowed per ATI project seems like a good number to show the failsafe message "I'm sorry, AnnoREP can't number annotations for projects with more than N annotations"? The number seems really high, I don't think any normal users would reach that number.

----
Do you have any thoughts on the order of the toggle UI in relation to the other form elements? I'd put it after "Add QDR information to annotations".

What about the label of the toggle UI? Does "Number annotations" sound good?

**Comment by adam3smith** [comment]
Thanks!

> Does 800,000 (80 million / 100 avg words per annotation) as a max number of annotations allowed per ATI project seems like a good number to show the failsafe message "I'm sorry, AnnoREP can't number annotations for projects with more than N annotations"? The number seems really high, I don't think any normal users would reach that number.

Let's not take any risk and set this to 10,000 annotations (which can then be quite long -- 10k words is the typical length of an academic article, so that'd be one annotation per word or one every sentence for a whole book. Neither of these will ever happen, but better not to take any risks with our server.

> Do you have any thoughts on the order of the toggle UI in relation to the other form elements? I'd put it after "Add QDR information to annotations".
What about the label of the toggle UI? Does "Number annotations" sound good?

Yes, I was thinking the same on both of those.

**Comment by tohuynh** [comment]
> Let's not take any risk and set this to 10,000 annotations

👍

**Comment by tohuynh** [comment]
@adam3smith This feature is ready to be tested on `stage`.

**Comment by tohuynh** [comment]
@adam3smith I successfully test exporting annotations with and without numbering for https://stage.anno-rep.org/ati/21589/manuscript.

I added the second `<br>` after `AN$n` was well.

The title annotation issue is an issue with ARCore server. Exporting annotation with "Include QDR Information" may not work on some data projects if the title annotation wasn't generated.

**Comment by adam3smith** [comment]
Thanks! I'll test tomorrow.

> The title annotation issue is an issue with ARCore server. Exporting annotation with "Include QDR Information" may not work on some data projects if the title annotation wasn't generated.

Question: in my tests, everything else (i.e. adding the QDR banner to all other annotations) still worked. Is the code written so that that's reliably the case? If so, that's fine, we can just insert the title annotations manually quite quickly.

If not, however, I'd rather do away with that annotation across the board, as adding the banners is the actually tedious part.

**Comment by tohuynh** [comment]
> Is the code written so that that's reliably the case?

Yes, code-wise, exporting annotations with the QDR banner is the same as exporting annotations without the QDR banner. The only difference is the text of the annotation is a little different to include the banner. 

> If not, however, I'd rather do away with that annotation across the board, as adding the banners is the actually tedious part.

Okay, let me stop Jim from implementing the "lob" change then.

**Comment by adam3smith** [comment]
(Also continued on Slack)

> Yes, code-wise, exporting annotations with the QDR banner is the same as exporting annotations without the QDR banner. The only difference is the text of the annotation is a little different to include the banner.

Right, but exporting with banner is handled by the same "include QDR information" toggle, so I'm worried that the error thrown by the title note could interrupt this as well. If it doesn't (e.g. if the title note is generate last) that's great.

As I said on Slack, it'd still be nice to have this; I just don't want it to break the more time-saving QDR-banner-adding functionality.

**Comment by tohuynh** [comment]
> If it doesn't (e.g. if the title note is generate last) that's great.

Yes, the title note is generated last. If the title note request does error, currently the status notification will show the error though.

**Comment by adam3smith** [comment]
> Yes, the title note is generated last. If the title note request does error, currently the status notification will show the error though.

Cool, that works then -- if we think we can just fix the error, that's be great, but otherwise making the error clearer, along the lines of:

> Could not create the title annotation on the target URL. All [number] annotations have been exported successfully with QDR information.

**Comment by tohuynh** [comment]
> but otherwise making the error clearer, 

I can make the change -- maybe with two status notifications instead of one, to keep the success notification green and error notification red.

**Comment by adam3smith** [comment]
All tests work fine now -- the title note for the problematic document got created on empty text at the bottom, but that's fine -- we can work with that. I think this is ready to go to production

**Comment by tohuynh** [comment]
> the title note for the problematic document got created on empty text at the bottom, but that's fine -- we can work with that. 

Yeah I redid the AnnoRep process for that project and this time ARCore created a title annotation anchored to the bottom;

>Jim: The first annotation is different than before and short. It looks like the core did not find a title in the doc since it expects the title to be Heading1 and this isn't. So I think the annotation file does have the extra title comment but it's anchor is at the end of the document.

**Comment by tohuynh** [comment]
Completed with #102, #103, and #104
